const permissions = {
  MANAGE_EVENTS: 'MANAGE_EVENTS',
  CHECK_IN_VISITORS: 'CHECK_IN_VISITORS',
  MANAGE_VISITORS: 'MANAGE_VISITORS',
  VIEW_REPORTS: 'VIEW_REPORTS',
  MANAGE_EXHIBITORS: 'MANAGE_EXHIBITORS',
  MANAGE_STAFF: 'MANAGE_STAFF',
};

module.exports = permissions;
